import type { AgentSeat, BuildCheck, Project, ReviewRecord, Task, TaskEvent } from "./types";

export const projects: Project[] = [
  {
    id: "tuohang-main-site",
    name: "Tuohang Main Site",
    phase: "Phase 1 Visual",
    status: "active",
    localPathPlaceholder: "~/Projects/tuohang-main-site",
    summary: "Marketing surface and office-grade launch pages.",
    accent: "cyan",
    agentSeatIds: ["seat-1"],
  },
  {
    id: "provider-workspace",
    name: "Provider Workspace",
    phase: "Phase 1 Prototype",
    status: "reviewing",
    localPathPlaceholder: "~/Projects/provider-workspace",
    summary: "Internal provider operations room with task handoff.",
    accent: "teal",
    agentSeatIds: ["seat-2"],
  },
  {
    id: "sanyang-temple-portal",
    name: "Sanyang Temple Portal",
    phase: "Content Map",
    status: "attention",
    localPathPlaceholder: "~/Projects/sanyang-temple-portal",
    summary: "Public cultural portal, ritual calendar, and visitor paths.",
    accent: "amber",
    agentSeatIds: [],
  },
  {
    id: "ai-concierge",
    name: "AI Concierge",
    phase: "Interaction Demo",
    status: "blocked",
    localPathPlaceholder: "~/Projects/ai-concierge",
    summary: "Local mock concierge panel for guided service flows.",
    accent: "red",
    agentSeatIds: ["seat-3"],
  },
  {
    id: "content-engine",
    name: "Content Engine",
    phase: "Editorial Ops",
    status: "quiet",
    localPathPlaceholder: "~/Projects/content-engine",
    summary: "Publishing pipeline prototype and review queue.",
    accent: "violet",
    agentSeatIds: [],
  },
];

export const agentSeats: AgentSeat[] = [
  {
    id: "seat-1",
    name: "Codex Seat 1",
    status: "editing",
    projectId: "tuohang-main-site",
    taskId: "task-hero-office",
    focus: "Shaping spatial office canvas",
  },
  {
    id: "seat-2",
    name: "Codex Seat 2",
    status: "waiting_review",
    projectId: "provider-workspace",
    taskId: "task-provider-review",
    focus: "Waiting for visual acceptance",
  },
  {
    id: "seat-3",
    name: "Codex Seat 3",
    status: "build_failed",
    projectId: "ai-concierge",
    taskId: "task-concierge-routing",
    focus: "Mock route check failed",
  },
];

export const tasks: Task[] = [
  {
    id: "task-hero-office",
    projectId: "tuohang-main-site",
    title: "Design office-style home command view",
    status: "running",
    priority: "critical",
    agentSeatId: "seat-1",
    acceptanceCriteria: ["Project rooms are spatial", "Busy seat is obvious", "Build wall is visible"],
    forbiddenScope: ["OpenAI API", "Real filesystem scan", "Git integration"],
    changedFiles: ["app/page.tsx", "components/office/OfficeMap.tsx", "components/layout/AppShell.tsx"],
  },
  {
    id: "task-provider-review",
    projectId: "provider-workspace",
    title: "Review provider workspace task board",
    status: "waiting_review",
    priority: "high",
    agentSeatId: "seat-2",
    acceptanceCriteria: ["Review room links work", "Mock diff is readable", "Approve state changes locally"],
    forbiddenScope: ["GitHub API", "Backend service", "Authentication"],
    changedFiles: ["components/tasks/TaskBoard.tsx", "components/review/ReviewPanel.tsx"],
  },
  {
    id: "task-concierge-routing",
    projectId: "ai-concierge",
    title: "Repair mock concierge room routing",
    status: "blocked",
    priority: "critical",
    agentSeatId: "seat-3",
    acceptanceCriteria: ["Blocked state is unmistakable", "Failed check appears in Build Wall"],
    forbiddenScope: ["Real npm command runner", "node-pty", "Codex CLI"],
    changedFiles: ["app/projects/[id]/page.tsx"],
  },
  {
    id: "task-temple-events",
    projectId: "sanyang-temple-portal",
    title: "Map temple event stream cards",
    status: "ready",
    priority: "medium",
    acceptanceCriteria: ["Events group by project", "Important event tones are distinct"],
    forbiddenScope: ["Remote CMS", "Cloud sync"],
    changedFiles: ["components/office/EventTicker.tsx"],
  },
  {
    id: "task-content-engine",
    projectId: "content-engine",
    title: "Draft content engine review lane",
    status: "backlog",
    priority: "medium",
    acceptanceCriteria: ["Backlog lane stays compact", "Project room remains quiet"],
    forbiddenScope: ["Database persistence"],
    changedFiles: ["lib/mock-data.ts"],
  },
  {
    id: "task-build-wall",
    projectId: "tuohang-main-site",
    title: "Tune mock build wall signal colors",
    status: "done",
    priority: "high",
    acceptanceCriteria: ["Passed, failed, running states differ", "No command execution"],
    forbiddenScope: ["Real quality gate commands"],
    changedFiles: ["components/office/BuildWall.tsx", "lib/status.ts"],
  },
  {
    id: "task-review-scope",
    projectId: "provider-workspace",
    title: "Show forbidden scope in Review Room",
    status: "waiting_review",
    priority: "high",
    agentSeatId: "seat-2",
    acceptanceCriteria: ["Forbidden scope is visible", "Changed files are mock-only"],
    forbiddenScope: ["Supabase", "Vercel webhook", "Payment"],
    changedFiles: ["components/review/ReviewPanel.tsx", "components/review/MockDiffSummary.tsx"],
  },
  {
    id: "task-map-motion",
    projectId: "sanyang-temple-portal",
    title: "Add subtle office map motion",
    status: "ready",
    priority: "low",
    acceptanceCriteria: ["Motion is restrained", "Reduced motion remains usable"],
    forbiddenScope: ["Canvas game layer"],
    changedFiles: ["components/office/OfficeMap.tsx"],
  },
];

export const buildChecks: BuildCheck[] = [
  { id: "check-1", projectId: "tuohang-main-site", taskId: "task-hero-office", label: "Mock TypeScript", status: "running", detail: "Component contracts scanning" },
  { id: "check-2", projectId: "tuohang-main-site", taskId: "task-build-wall", label: "Visual Build", status: "passed", detail: "Build wall states aligned" },
  { id: "check-3", projectId: "provider-workspace", taskId: "task-provider-review", label: "Review Flow", status: "passed", detail: "Local decision state works" },
  { id: "check-4", projectId: "ai-concierge", taskId: "task-concierge-routing", label: "Mock Route Audit", status: "failed", detail: "Review link target mismatch" },
  { id: "check-5", projectId: "sanyang-temple-portal", taskId: "task-temple-events", label: "Event Density", status: "pending", detail: "Waiting for office map pass" },
  { id: "check-6", projectId: "content-engine", taskId: "task-content-engine", label: "Editorial Lane", status: "skipped", detail: "Backlog only" },
  { id: "check-7", projectId: "provider-workspace", taskId: "task-review-scope", label: "Scope Guard", status: "passed", detail: "Forbidden scope displayed" },
  { id: "check-8", projectId: "sanyang-temple-portal", taskId: "task-map-motion", label: "Motion Comfort", status: "pending", detail: "Reduced motion pass queued" },
];

export const taskEvents: TaskEvent[] = [
  { id: "event-1", projectId: "tuohang-main-site", taskId: "task-hero-office", agentSeatId: "seat-1", time: "09:12", tone: "info", message: "Seat 1 opened the office canvas task." },
  { id: "event-2", projectId: "tuohang-main-site", taskId: "task-hero-office", agentSeatId: "seat-1", time: "09:18", tone: "success", message: "Spatial project room layout drafted." },
  { id: "event-3", projectId: "provider-workspace", taskId: "task-provider-review", agentSeatId: "seat-2", time: "09:25", tone: "warning", message: "Provider board moved into review queue." },
  { id: "event-4", projectId: "ai-concierge", taskId: "task-concierge-routing", agentSeatId: "seat-3", time: "09:31", tone: "danger", message: "Mock route audit failed in concierge project." },
  { id: "event-5", projectId: "tuohang-main-site", taskId: "task-build-wall", time: "09:36", tone: "success", message: "Build wall color language approved in mock state." },
  { id: "event-6", projectId: "sanyang-temple-portal", taskId: "task-temple-events", time: "09:42", tone: "info", message: "Temple event stream is ready for assignment." },
  { id: "event-7", projectId: "content-engine", taskId: "task-content-engine", time: "09:47", tone: "info", message: "Content engine task parked in backlog." },
  { id: "event-8", projectId: "provider-workspace", taskId: "task-review-scope", agentSeatId: "seat-2", time: "10:02", tone: "warning", message: "Review room now highlights forbidden scope." },
  { id: "event-9", projectId: "ai-concierge", taskId: "task-concierge-routing", agentSeatId: "seat-3", time: "10:14", tone: "danger", message: "Seat 3 marked blocked pending route correction." },
  { id: "event-10", projectId: "tuohang-main-site", taskId: "task-hero-office", agentSeatId: "seat-1", time: "10:21", tone: "info", message: "Office home active task remains in progress." },
  { id: "event-11", projectId: "sanyang-temple-portal", taskId: "task-map-motion", time: "10:33", tone: "info", message: "Map motion task queued with low priority." },
  { id: "event-12", projectId: "provider-workspace", taskId: "task-provider-review", time: "10:48", tone: "success", message: "Review action buttons wired to mock UI state." },
];

export const reviewRecords: ReviewRecord[] = [
  {
    taskId: "task-provider-review",
    diffSummary: ["Added task lane density rules", "Connected review links to mock tasks", "Refined waiting review status treatment"],
    riskNotes: ["No backend operation is performed", "Review decision resets on page reload"],
    qualityGateIds: ["check-3", "check-7"],
    decision: "pending",
  },
  {
    taskId: "task-review-scope",
    diffSummary: ["Displayed acceptance criteria and forbidden scope side by side", "Added mock changed file list", "Improved review room hierarchy"],
    riskNotes: ["Uses mock filenames only", "Future real diff integration remains out of scope"],
    qualityGateIds: ["check-7"],
    decision: "pending",
  },
  {
    taskId: "task-concierge-routing",
    diffSummary: ["Identified missing mock route target", "Marked blocked task in office home", "Surfaced failed build wall row"],
    riskNotes: ["Failure is intentionally simulated", "No route scanner or command runner exists"],
    qualityGateIds: ["check-4"],
    decision: "pending",
  },
];
