import type { LocalPermissionModel } from "./safety-types";

export function createLocalPermissionModel(): LocalPermissionModel {
  return {
    approvedPathPermission: {
      state: "requires_approval",
      summary: "Project-local access requires an explicitly approved path before any scoped runner action; actual configured/approved state is read from local DB views.",
      configured: false,
      approved: false,
      manualOnly: true,
      noAutoScan: true,
      noSourceRead: true,
    },
    runnerPermission: {
      state: "allowed",
      summary: "Only the scoped Codex runner model is allowed; arbitrary shell, terminal UI, node-pty, auto Git mutation, and auto deploy stay blocked.",
      scopedRunnerOnly: true,
      approvedPathRequired: true,
      shellFalse: true,
      noArbitraryShell: true,
      noCommandTextbox: true,
      noTerminal: true,
      noNodePty: true,
      noAutoGitMutation: true,
      noAutoDeploy: true,
    },
    backupPermission: {
      state: "allowed",
      summary: "Backups are local-only SQLite backups and must not include source trees, tokens, auth files, or environment files.",
      sqliteOnly: true,
      localOnly: true,
      restoreRequiresDryRun: true,
      restoreRequiresConfirm: true,
      safetyBackupBeforeRestore: true,
      noSourceBackup: true,
      noTokenBackup: true,
    },
    archivePermission: {
      state: "allowed",
      summary: "Archive behavior is dry-run oriented and must not perform real deletion, backup deletion, or scheduled cleanup.",
      dryRunOnly: true,
      noRealDeletion: true,
      noBackupFileDeletion: true,
      noScheduledCleanup: true,
    },
    launcherPermission: {
      state: "allowed",
      summary: "Launcher behavior is localhost/status-only and must not start dev servers or execute Codex, Git, or quality commands.",
      localhostOnly: true,
      statusOnlyDefault: true,
      noDevServerStart: true,
      noCodexGitQualityExecution: true,
    },
    tauriPermission: {
      state: "allowed",
      summary: "Tauri stays prototype/core-default only with no production installer, updater, shell plugin, or filesystem expansion.",
      prototypeOnly: true,
      noProductionInstaller: true,
      noUpdater: true,
      noShellPlugin: true,
      noFsExpansion: true,
      coreDefaultOnly: true,
    },
    cloudPermission: {
      state: "blocked",
      summary: "Cloud sync and external service integration are blocked for the local-first safety model.",
      cloudSyncDisabled: true,
      githubApiDisabled: true,
      vercelDisabled: true,
      supabaseDisabled: true,
    },
    credentialPermission: {
      state: "blocked",
      summary: "Credential, auth, token, secret, private key, and env-file access is blocked.",
      noAuthJsonRead: true,
      noEnvRead: true,
      noTokenStorage: true,
      noOpenAiApi: true,
    },
  };
}
